### PR TITLE
Creating a PR to start a discussion of world-domination

### PR DESCRIPTION
**Pull request by brugeman**
Some feedback/ideas.

On this: https://github.com/erskingardner/nostr-how/blob/main/world-domination.md#so-how-do-we-get-builders-excited

I agree that marketplace/platform building will apply, but at this point I'd say the major driver is just curiosity/enthusiasm/desire to belong/work on a frontier. We don't have too many users or great monetization ideas (although LN+zaps are definitely promising), so trying to attract devs/teams based on purely rational arguments might be premature.

And again, atm tools/docs/etc are secondary things IMO, curious devs will find their way, it's not the ease of development/tools that attracts them, it might be precisely the opposite - empty plate, where YOU can build up the tools etc.

So my answer to "how do we get builders excited" - explain to them the possibilities, give some hints/ideas. That's probably enough. They'll figure out the "how". 

Later on, when we have better answers for 'users' and 'monetization' questions, more business oriented devs/teams will come, that's where we need a lot of dev tools/docs to reduce friction for them.

On https://github.com/erskingardner/nostr-how/blob/main/world-domination.md#low-time-preference-incentives

Agree that we should attract believers/curious. Agree we need to build up financial/user-base incentives. Not 100% agree that new devs should be freedom-oriented and ideological - I think curiosity is enough, with that we're more likely to come up with something that actually works.

Result sharing will probably happen organically, precisely bcs there is not yet a business to be made, and the only real "value" you get is being part of the community of builders, which means you'd have to share. But if someone comes up with a nice idea on nostr that works and doesn't share their "secrets" - that's fine too, they'd still grow nostr and that's what we need.

On https://github.com/erskingardner/nostr-how/blob/main/world-domination.md#potential-growth-projects

I feel like today 99% of discussion on Nostr is about it being a twitter-clone. There are 500+ repos on github w/ "nostr" tag, yet maybe 20 of them get any attention. That's not a community of builders, that's a twitter-clone bitcoin-discussing community.

So [design.nostr.how](http://design.nostr.how/) and [dev.nostr.how](http://dev.nostr.how/) are good ideas, any effort to give more visibility and praise to new projects/libs are good. More podcasts w/ devs, more integrations btw apps, etc. No need to make all of those new things a new NIP atm - that's too much friction, just encourage people to play more and appreciate their work. 

Meetups, confs, PH/HN/SO/IH are good (talk there, but also maybe replicate some of that experience on/around nostr). 

I also think nostrocket might be a good thing to experiment here, or at least some aspects of it. Like
- here are list of potential ideas that someone wants to be built (or submit your own wish/idea/pitch)
- here are people willing to zap a builder that tries to work on these ideas (or _any_ ideas)
- here are people willing to help (design, UX, content etc), like Karnage, Tony, eetc
- here is a process to "apply" for various sources of financing - by zappers, nostrocket-style investors, opensats, etc
- here are people willing to try every new thing and give feedback
- etc for further stages of app lifecycle

PH/IH combined w/ YC for earliest stage possible. That's what I think is worth trying.

### CODE REVIEW

**Comment by brugeman** [comment]
Also, if we look at nostr as an app ecosystem/infrastructure, then we're using a 100% wrong metrics to measure it's success (stuff like stats.nostr.band). Better metrics would be: number of github repos w/ 'nostr', number of useful data kinds, number of events kind (aside from kinds 0,1,6,7), number of successful fundraisers for app builders, number of builders - devs/designers/testers/investors/etc. And I'd say that by those metrics we're definitely growing, vs the stagnating number of active users of twitter-style use case.

**Comment by erskingardner** [comment]
@karnagebitcoin Would love your feedback here too.

**Comment by madelainemichele** [comment]
Hello! Hope it's ok if I leave some comments here. I feel that a turning point for growth will be when people on nostr are able to stop using Telegram (or similar platforms) and just find nostr easier to use for these text communications. The recent discussions to improve direct messages seem promising. Privacy will be a great selling point when it is optimized. The lack of privacy for direct message metadata is also stopping marketplaces from being implemented. 

An idea to supercharge growth today would be to recruit a content creator with a significant amount of followers on a centralized platform and walk them through the process of setting up their own private relay with users paying to gain writing access with other added benefits. Content creators would then truly own their content on their own personal relay and receive monetary compensation directly.

Also Pablo’s recent note about having nostr nests chats for new developers and having these recordings available for others would be a great resource for new builders.

**Comment by erskingardner** [comment]
Thanks for the comments @madelainemichele – definitely helpful!

**Comment by erskingardner** [comment]
> 
Also, if we look at nostr as an app ecosystem/infrastructure, then we're using a 100% wrong metrics to measure it's success (stuff like stats.nostr.band). Better metrics would be: number of github repos w/ 'nostr', number of useful data kinds, number of events kind (aside from kinds 0,1,6,7), number of successful fundraisers for app builders, number of builders - devs/designers/testers/investors/etc. And I'd say that by those metrics we're definitely growing, vs the stagnating number of active users of twitter-style use case.

yeah – I agree. The social use-case metrics aren't at all what we should be looking at. I read somewhere (can't remember where but Bill Gates comes to mind) that the value of a platform is the value of the economic activity that happens on top of the platform, that wouldn't have otherwise been able to happen). It's basically an unmeasurable thing but I like to keep that in mind when thinking about Nostr.

**Pull request closed without merging**
