### PR TITLE
Start Posting Notes page

### PR DESCRIPTION
**Pull request by boston-wine**
A page for getting started creating notes. I think I'm doing this right...

### CODE REVIEW

**Review by erskingardner — APPROVED** [review]

**Comment by erskingardner** [comment]
@boston-wine I noticed that we actually already have a setup zapping wallet page as a guide: https://nostr.how/en/guides/setup-zapping-wallet

Do you think your new page should replace this guide or should we just keep what we have?

**Comment by boston-wine** [comment]
Hey @erskingardner apologies for any confusion - the only new content should be the "start posting notes" page. The zapping wallet guide I created does need some updates/edits, but I did not include those changes in this PR. Happy to submit a separate PR with those changes once I've got them done right.

And let me know if there was a cleaner way to submit this PR that wouldn't imply changes to the older page ;)

Thanks!

> @boston-wine I noticed that we actually already have a setup zapping wallet page as a guide: https://nostr.how/en/guides/setup-zapping-wallet
> 
> Do you think your new page should replace this guide or should we just keep what we have?

**Comment by erskingardner** [comment]
you're going to need to either create a new commit deleting or moving the zapping wallet page into a _drafts folder or something. Right now, both files are still in the PR and they will both show up on the site if merged. 

While you're at it, one other thing you can do is to add the start posting notes page to the sidebar nav, which lives in the `Sidebar.svelte` component.

**Review by erskingardner — APPROVED** [review]

**Comment by erskingardner** [comment]
Is this ready for a merge now?

**Comment by boston-wine** [comment]
Closing this PR as it's been a while and I'd rather re-sync my fork and open a new PR. Learning as I go.

**Pull request closed without merging**
