### PR TITLE
Portuguese Translation

### PR DESCRIPTION
**Pull request by vitoshi21**
* #1 added pt, translated menu entries and get started page

* added what is nostr and why nostr pages

* #1 added the protocol

* added zaps and amethyst

* #1 added relays and relay-implementations

* added manage your sats

* 1-tradução-para-o-português: Added get verified

* #1 added clients

* #1 added sweep to self custody

* #1 added nostr projects

* #1 added contribute

* #1 added setup zapping wallet

* #1 fixed typos

* #1 added astral

* #1 added damus

* #1 added iris and nostr chat

* Update what-is-nostr.md

* Update zaps.md

fixed typo

* fixed typo

* fixed typo

* fixed typo

* fixed typos

* Update zaps.md

* Update why-nostr.md

* Update why-nostr.md

* Update what-is-nostr.md

* Update src/routes/pages/pt/what-is-nostr.md

* Update src/routes/pages/pt/clients.md

* Update src/routes/pages/pt/clients.md

* Update src/routes/pages/pt/clients.md

* Update src/routes/pages/pt/contribute.md

* Update src/routes/pages/pt/clients.md

* Update what-is-nostr.md

---------

### CODE REVIEW

**Comment by vitoshi21** [comment]
also live on nostr.pt

**Review by erskingardner — APPROVED** [review]
Amazing!

**Comment by erskingardner** [comment]
Thanks a million @vitoshi21 one thing I noticed on nostr.pt. you seem to have the persian link twice in the language selector. the code here looks fine but worth a check on your version.

**Comment by vitoshi21** [comment]
> Thanks a million @vitoshi21 one thing I noticed on nostr.pt. you seem to have the persian link twice in the language selector. the code here looks fine but worth a check on your version.

Hey! Thank you for starting this project!

Yes, I noticed that problem when I opened this PR and made a quick fix but I have not deployed it yet on nostr.pt, will deploy soon.

Cheers!

**Pull request merged**
